<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleAndPermissionSeeder extends Seeder
{
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // 1. Programmatically run Filament Shield generator to generate all PascalCase permissions & policies
        Artisan::call('shield:generate', [
            '--all' => true,
            '--panel' => 'admin',
            '-n' => true
        ]);

        // 2. Create Roles and assign permissions
        $superAdmin = Role::firstOrCreate(['name' => 'Super Admin']);
        // Super Admin gets all permissions in the database
        $superAdmin->syncPermissions(Permission::all());

        $adminDPP = Role::firstOrCreate(['name' => 'Admin Pusat (DPP)']);
        // DPP also gets all permissions
        $adminDPP->syncPermissions(Permission::all());

        // Helper map for other administrative roles
        $adminDPWPermissions = [
            'view_any_province', 'view_province',
            'view_any_regency', 'view_regency', 'create_regency', 'update_regency',
            'view_any_district', 'view_district', 'create_district', 'update_district',
            'view_any_village', 'view_village', 'create_village', 'update_village',
            'view_any_position', 'view_position',
            'view_any_member', 'view_member', 'create_member', 'update_member',
            'view_any_committee', 'view_committee', 'create_committee', 'update_committee', 'delete_committee',
            'view_any_inventory', 'view_inventory', 'create_inventory', 'update_inventory', 'delete_inventory',
            'view_any_event', 'view_event', 'create_event', 'update_event', 'delete_event',
            'view_any_document', 'view_document', 'create_document', 'update_document', 'delete_document',
            'view_any_attendance', 'view_attendance', 'create_attendance', 'update_attendance', 'delete_attendance',
        ];

        $adminDPW = Role::firstOrCreate(['name' => 'Admin Wilayah (DPW)']);
        $adminDPW->syncPermissions($this->getMappedPermissions($adminDPWPermissions));

        $adminDPCPermissions = [
            'view_any_province', 'view_province',
            'view_any_regency', 'view_regency',
            'view_any_district', 'view_district', 'create_district', 'update_district',
            'view_any_village', 'view_village', 'create_village', 'update_village',
            'view_any_position', 'view_position',
            'view_any_member', 'view_member', 'create_member', 'update_member',
            'view_any_committee', 'view_committee', 'create_committee', 'update_committee', 'delete_committee',
            'view_any_inventory', 'view_inventory', 'create_inventory', 'update_inventory', 'delete_inventory',
            'view_any_event', 'view_event', 'create_event', 'update_event', 'delete_event',
            'view_any_document', 'view_document', 'create_document', 'update_document', 'delete_document',
            'view_any_attendance', 'view_attendance', 'create_attendance', 'update_attendance', 'delete_attendance',
        ];

        $adminDPC = Role::firstOrCreate(['name' => 'Admin Cabang (DPC)']);
        $adminDPC->syncPermissions($this->getMappedPermissions($adminDPCPermissions));

        $adminPACPermissions = [
            'view_any_province', 'view_province',
            'view_any_regency', 'view_regency',
            'view_any_district', 'view_district',
            'view_any_village', 'view_village',
            'view_any_position', 'view_position',
            'view_any_member', 'view_member', 'create_member', 'update_member',
            'view_any_committee', 'view_committee', 'create_committee', 'update_committee',
            'view_any_inventory', 'view_inventory', 'create_inventory', 'update_inventory',
            'view_any_event', 'view_event', 'create_event', 'update_event',
            'view_any_document', 'view_document', 'create_document', 'update_document',
            'view_any_attendance', 'view_attendance', 'create_attendance', 'update_attendance',
        ];

        $adminPAC = Role::firstOrCreate(['name' => 'Admin Kecamatan (PAC)']);
        $adminPAC->syncPermissions($this->getMappedPermissions($adminPACPermissions));

        // 3. Create default Super Admin user
        $user = User::firstOrCreate(
            ['email' => 'admin@ppp.com'],
            [
                'name' => 'Super Administrator',
                'password' => bcrypt('password'),
            ]
        );
        $user->assignRole('Super Admin');
    }

    /**
     * Map old snake_case permissions to new PascalCase permissions generated by Shield.
     */
    private function getMappedPermissions(array $oldPermissions): array
    {
        $entityMap = [
            'province' => 'Province',
            'regency' => 'Regency',
            'district' => 'District',
            'village' => 'Village',
            'position' => 'Position',
            'member' => 'User',
            'committee' => 'Committee',
            'inventory' => 'Inventory',
            'event' => 'Event',
            'document' => 'Document',
            'attendance' => 'Attendance',
            'tps' => 'Tps',
            'office' => 'Office',
            'article' => 'Article',
        ];

        $mapped = [];

        foreach ($oldPermissions as $old) {
            if ($old === 'manage_roles') {
                $mapped[] = 'ViewAny:Role';
                $mapped[] = 'View:Role';
                $mapped[] = 'Create:Role';
                $mapped[] = 'Update:Role';
                $mapped[] = 'Delete:Role';
                continue;
            }

            if ($old === 'manage_users') {
                continue;
            }

            $action = '';
            $entity = '';

            if (str_starts_with($old, 'view_any_')) {
                $action = 'ViewAny';
                $entity = substr($old, 9);
            } elseif (str_starts_with($old, 'view_')) {
                $action = 'View';
                $entity = substr($old, 5);
            } elseif (str_starts_with($old, 'create_')) {
                $action = 'Create';
                $entity = substr($old, 7);
            } elseif (str_starts_with($old, 'update_')) {
                $action = 'Update';
                $entity = substr($old, 7);
            } elseif (str_starts_with($old, 'delete_')) {
                $action = 'Delete';
                $entity = substr($old, 7);
            } else {
                $mapped[] = $old;
                continue;
            }

            $mappedEntity = $entityMap[$entity] ?? ucfirst($entity);
            
            // Add basic actions
            $mapped[] = "{$action}:{$mappedEntity}";
            
            // For ViewAny, also add Reorder/Replicate if necessary, or just stick to basic mapping
        }

        // Fetch corresponding Spatie permissions from database
        return Permission::whereIn('name', array_unique($mapped))->pluck('name')->toArray();
    }
}
